name: widget_preview_scaffold
description: Scaffolding for Flutter Widget Previews
publish_to: none
version: 0.0.1
environment:
  sdk: ^3.10.1
dependencies:
  dtd: ^4.0.0
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0
  google_fonts: ^4.0.4
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  thali_help:
    path: ../..
  url_launcher: ^6.3.2
  web: ^1.1.1
flutter:
  uses-material-design: true
dependency_overrides:
  thali_help:
    path: ../..
